name: push-in-other-repository
on: push

jobs:
    push-other-repository:
        runs-on: ubuntu-latest
        name: Push in other repository

        steps:
        - name: Get repository A
          id: repoA
          uses: actions/checkout@main
          with:
            path: ./pruebaAction

        - name: Get repository B
          id: repoB
          uses: actions/checkout@main
          with: 
            repository: angelcanada0/action-destino
            token: ${{ secrets.API_TOKEN_GITHUB }}
            path: ./action-destino

        - name: docker login
          env: 
            DOCKER_USER: ${{ secrets.DOCKER_USER }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

        - name: Docker info
          run: |
            docker info

        
            
        - name: Push repository destination
          run: |
            cd ./action-destino
            echo README.md > test.txt
            git add .
            git config user.name angelcanada0
            git config user.email angel.canada.munoz@accenture.com
            git commit -am "Repository push into repository destination"
            git push

