name: push-in-other-repository
on: 
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
    push-other-repository:
        runs-on: ubuntu-latest
        name: Push in other repository

        steps:
        - name: Get repository A
          id: repoA
          uses: actions/checkout@main
          with:
            path: ./pruebaAction

        - name: Get repository B
          id: repoB
          uses: actions/checkout@main
          with: 
            repository: angelcanada0/action-destino
            token: ${{ secrets.API_TOKEN_GITHUB }}
            path: ./action-destino

        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v3
          with:
            images: name/app
            tags: |
              type=ref,event=branch
              type=ref,event=pr
              type=match,pattern=\d.\d.\d

        - name: docker login
          env: 
            DOCKER_USER: ${{ secrets.DOCKER_USER }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

        - name: Docker info
          run: |
            docker info

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./pruebaAction
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
     
        - name: Push repository destination
          run: |
            cd ./action-destino
            echo "Version 1" > test.txt
            git add .
            git config user.name angelcanada0
            git config user.email angel.canada.munoz@accenture.com
            git tag v0.0.1 -m "Primera version"
            git commit -am "Repository push into repository destination"
            git push --tags

