name: push-in-other-repository
on: push

jobs:
    push-other-repository:
        runs-on: ubuntu-latest
        name: Push in other repository

        steps:
        - name: Get repository A
          uses: actions/checkout@main
          with:
            path: ./pruebaAction

        - name: Push repository destination
          run: |
            
            git remote add origin https://github.com/angelcanada0/action-destino.git
            git push origin master

