name: push-in-other-repository
on: push

jobs:
    push-other-repository:
        runs-on: ubuntu-latest
        name: Push in other repository

        steps:
        - name: Get repository A
          uses: actions/checkout@main
          with:
            path: ./pruebaAction

        - name: Get repository B
          uses: angelcanada0/action-destino@main
          id: repositoryB
          with:
            path: ./action-destino

        - name: Push repository destination
          run: |
            mkdir action-destino
            cd ./action-destino
            git clone https://github.com/angelcanada0/pruebaAction.git

            git remote set-url origin https://github.com/angelcanada0/action-destino.git
            git push -u origin master
