name: push-in-other-repository
on: push

jobs:
    push-other-repository:
        runs-on: ubuntu-latest
        name: Push in other repository

        steps:
        - name: Get repository A
          id: repoA
          uses: actions/checkout@main
          with:
            path: ./pruebaAction



        - name: Push repository destination
          run: |
            cd ./action-destino
            echo "Prueba 2" > test.txt
            git add .
            git config user.name angelcanada0
            git config user.email angel.canada.munoz@accenture.com
            git commit -am "Repository push into repository destination"
            git push

