name: push-in-other-repository
on: push

jobs:
    push-other-repository:
        runs-on: ubuntu-latest
        name: Push in other repository

        steps:
          - uses: actions/checkout@v2
          - name: Pushes to another repository
            id: push_directory
            uses: angelcanada0/action-destino@main
            env:
              API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
            with:
              source-directory: 'output'
              destination-github-username: 'angelcanada0'
              destination-repository-name: 'action-destino'
              user-email: angel.canada.munoz@accenture.com
              commit-message: See ORIGIN_COMMIT
              target-branch: main
