name: push-in-other-repository
on: push

jobs:
    push-other-repository:
        runs-on: ubuntu-latest
        name: Push in other repository

        steps:
        - name: Get repository A
          uses: actions/checkout@v2
          with:
            path: ./pruebaAction

        - name: Get repository B
          uses: actions/checkout@master
          with: 
            repository: angelcanada0/action-destino
            token: ${{ secrets.API_TOKEN_GITHUB }}
            path: ./action-destino

        - name: Push repository destination
          run: |
            cd ./action-destino
            git add .
            git config user.name angelcanada0
            git config user.email angel.canada.munoz@accenture.com
            git commit -am "Repository push into repository destination"
            git push
